# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cad3503678bed7ba320939b57ab96133b4499de2e2e32ee23aaa7f6322d0db2c3420a9314582a7cab87189dbe32509047891935064bef2f421c4db5f2141ffa

test:
  secret_key_base: e2c773628d47a19dd50475b154a6095e732e226b753a4685d49579cf1db316e4197a1cf3757bc32428210d2b50f8c18c0ac5ad23940873a5966a279e28f5e477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
